### ISSUE TITLE
 More documentation is required！

### ISSUE THREAD

**Issue by eatingtomatoes** [YichengDWu/MoYe.jl#100]
Hi Wu, thank you for the work on MoYe.jl.

Please provide more documentation about the api and underlying computing principles. 

Without enough explanation, the "layout algebra" is really difficult to understand and to use.

Maybe you want me to look at CuTe's documentation, but I'm actually trying to understand CuTe through your documentation : ).

**Comment by eatingtomatoes** [comment]
The documentation about "complement" is very good.

**Comment by YichengDWu** [comment]
Hi, thanks for your interest!

Could you be more specific on which api is lacking documentation? I'm afraid I do not have the time lately for a massive update.

Another way to learn CuTe is to run MoYe.jl in the Julia REPL and check the outputs, I hope you will have fun doing it.

**Comment by YichengDWu** [comment]
> Developing Optimal CUDA Kernels on Hopper Tensor Cores | NVIDIA On-Demand

I believe that you will find the answer in the [Developing Optimal CUDA Kernels on Hopper Tensor Cores | NVIDIA On-Demand](https://www.nvidia.com/en-us/on-demand/session/gtcspring23-s51413/), starting from 17:38.
> having a REPL is very convenient. So I will try it.

It is highly encouraged to do so. MoYe.jl is heavily tested to produce the same output as CuTe.

**Comment by eatingtomatoes** [comment]
> I believe that you will find the answer in the [Developing Optimal CUDA Kernels on Hopper Tensor Cores | NVIDIA On-Demand](https://www.nvidia.com/en-us/on-demand/session/gtcspring23-s51413/), starting from 17:38. 

This talk is very helpful! I am surprised that they didn't include the link in CuTe's document.

I'm really grateful for your help. Thank you again!

**Comment by YichengDWu** [comment]
Let me know if you have any other questions, I'm more happy to answer them!

**Comment by eatingtomatoes** [comment]
I have been busy with other things recently and have not continued to study CUTLASS/CuTe/MoYe.jl.

Honestly, all I've ever wanted to do is to fuse two small matrix multiplications together. NV already did [that](https://github.com/NVIDIA/cutlass/tree/main/examples/13_two_tensor_op_fusion), using CUTLASS 2.x .

I tried to repeat it, using the 3.x api, but was blocked by the details of TiledCopy.

So I put this matter aside, hoping that the next release of CUTLASS will provide more documentation.

**Comment by YichengDWu** [comment]
That's quite understandable, I'm also waiting for the next docs release.
